#!/bin/bash
#Include file lib in same dir as this file
. $(dirname $0)"/lib"

sudo docker run -it --rm \
        -p 8069:8069 \
        -v ~/odoo-7.0/makeover/config:/etc/odoo \
        -v ~/odoo-7.0/makeover/data_dir:/var/lib/odoo \
        -v ~/odoo-7.0/sources:/mnt/extra-addons \
	--entrypoint=/bin/bash \
        --link db-odoo:db \
        --name makeover \
	    ${ODOO} $*
