#!/bin/bash
#Include file lib in same dir as this file
. $(dirname $0)"/lib"

sudo docker run -it --rm \
        --link aeroo_docs:aeroo \
        -p 8069:8069 \
        -v ~/odoo80/str/config:/etc/odoo \
        -v ~/odoo80/str/data_dir:/var/lib/odoo \
        -v ~/odoo80/sources:/mnt/extra-addons \
        --link db-odoo:db \
        --name str \
	    ${ODOO} $*
