#!/bin/bash
#Include file lib in same dir as this file
. $(dirname $0)"/lib"
#set -x
#
# add this line to sudo crontab -e to backup twice a day
#  m h  dom mon dow   command
#  0 0,12 *   *   *   host-backup odoo orto >> /var/log/bkp.log
#  0 0    *   *   1   housekeeping >> /var/log/bkp.log
#

ERROR=0
CUSTOMER=$1
DB=$2
DATE=$(date +"%Y %m %d %H:%M")

docker run --rm -i \
  --name bkp \
  --link db-odoo:db \
  --volumes-from $CUSTOMER \
  -v ~/odoo80/backup:/backup  \
  --env DBNAME=$DB jobiols/backup backup &> /var/log/$CUSTOMER.backup.log
if [ $? -ne 0 ]
  then
    msgerror "${DATE} Backup for client ${CUSTOMER} with db ${DB} failed!"
    exit 1
fi
msgdone "${DATE} Backup for client ${CUSTOMER} with db ${DB} successfuly done"

