#!/bin/sh
path=~/odoo80/backup
logfile=/var/log/housekeeping.log
date=$(date +"%Y %m %d %H:%M")

rm -f $logfile
for file in `find $path/* -mtime +30 -type f`
do
  echo "deleting: " $file >> $logfile
  rm $file
done
echo ${date} "deleting 30 days old files"

