#!/bin/sh
#Include file lib in same dir as this file
. $(dirname $0)"/lib"

path=~/odoo80/backup
logfile=/var/log/housekeeping.log
date=$(date +"%Y %m %d %H:%M")

rm -f $logfile
for file in `find $path/* -mtime +30 -type f`
do
  msginfo "deleting:  ${file}" >> $logfile
  rm $file
done
msginfo ${date} "deleting 30 days old files"

