#!/bin/bash
################################
#Include file lib in same dir as this file
#. $(dirname $0)"/lib"
###########################################################
#set -x
readonly RED="\e[31m"
readonly YELLOW="\e[33m"
readonly GREEN="\e[32m"
readonly STD="\e[0m"

function msginfo {
    echo -e "${STD}$1"
}
function msgrun {
    echo -e "${YELLOW}$1...${STD}"
}
function msgdone {
    echo -e "${GREEN}$1${STD}"
}
function msgerror {
    echo -e "${RED}ERROR: $1${STD}"
}
###########################################################

if [ $# -lt 3 ]
  then
    msgerror "Too few arguments supplied!"
    msginfo "Command: db-restore [customer] [db] [timestamp]"
    msginfo "Example: db-restore jeo jeo_datos 201511022241"
    exit 0
fi

CUSTOMER=$1
DB=$2
DATE=$3
DIR="/home/jorge/odoo-8.0/$CUSTOMER/backup"

docker run --rm -t \
       --volumes-from $CUSTOMER \
       -v $DIR:/backup \
       --link db-odoo:db \
       --env DBNAME=$DB \
       --env DATE=$DATE \
       jobiols/backup \
       restore 

if [ $? -ne 0 ]
  then
    msgerror "Restore for ${CUSTOMER} with  ${DB} failed!"
    exit 1
fi

msgdone "Restore for ${CUSTOMER} with ${DB} at ${DATE} successfully done"