#!/bin/bash
################################
#Include file lib in same dir as this file
. $(dirname $0)"/lib"

if [ $# -lt 3 ]
  then
    msgerror "Too few arguments supplied!"
    msginfo "Command: host-restore [customer] [db] [timestamp]"
    exit 0
fi

CUSTOMER=$1
DB=$2
DATE=$3

docker run --rm -t \
       --volumes-from $CUSTOMER \
       -v ~/odoo80/backup:/backup \
       --link db-odoo:db \
       --env DBNAME=$DB \
       --env DATE=$DATE \
       jobiols/backup \
       restore 

if [ $? -ne 0 ]
  then
    msgerror "Restore for ${CUSTOMER} with  ${DB} failed!"
    HASERROR=1
  else
  msgdone "Restore for ${DB} successful done$"
fi
