#!/bin/bash
# Start developer mode container
###############################################
echo -e "\n=== Starting odoo V8 on developer mode ==="
sudo docker run -d \
    --name db  \
    -e POSTGRES_PASSWORD=odoo \
    -e POSTGRES_USER=odoo \
    -v /home/ubuntu/80/data:/var/lib/postgresql/data \
    postgres:9.3.6

sudo docker run -d -p 8989:8989 \
    --name aeroo_docs  \
    rvalyi/aeroocker

sudo docker run -d -p 80:8069 \
    --name odoo \
    --link db:db \
    -v /home/ubuntu/80/filestore:/home/odoo \
    -v /home/ubuntu/80/addons:/opt/odoo/custom/addons \
    jobiols/odoo:80

