#!/bin/bash
# stop and remove all instances
###############################################
echo -e "\n=== Stopping odoo v7 ==="
sudo docker stop odoo
sudo docker stop db

sudo docker rm odoo
sudo docker rm db
