#!/bin/bash
# stop and remove all instances
###############################################
echo -e "\n=== Stopping odoo v7 ==="
sudo docker stop odoo
sudo docker stop db
sudo docker stop aeroo_docs

sudo docker rm odoo
sudo docker rm db
sudo docker rm aeroo_docs