#!/bin/bash
##############################################################
# Extract odoo sources to host
# va a borrar y crear un directorio /odoo/odoo-10.0/sources/odoo
# esto es para la imagen oficial odoo:10.0
# dentro de la imagen correr cp -r /usr/lib/python2.7/dist-packages/odoo/* /mnt/extra-addons/odoo

sudo rm -r /odoo/odoo-10.0/sources/odoo
sudo mkdir /odoo/odoo-10.0/sources/odoo
sudo chmod -R o+w /odoo/odoo-10.0/sources/odoo
sudo chown jorge.jorge /odoo/odoo-10.0/sources/odoo

sudo docker run -it --rm \
	--entrypoint=/bin/bash \
	-v /odoo/odoo-10.0/sources/odoo/:/mnt/extra-addons/odoo \
        odoo:10.0 $*
