#!/bin/bash
##############################################################
# Extract odoo sources to host
# crea e inicializa un directorio /odoo/odoo-8.0/sources/openerp
# entra en la imagen mapeando el directorio
# dentro de la imagen correr /extract-sources 

sudo rm -r /odoo/odoo-8.0/sources/openerp
sudo mkdir /odoo/odoo-8.0/sources/openerp
sudo chmod -R o+w /odoo/odoo-8.0/sources/openerp
sudo chown jorge.jorge /odoo/odoo-8.0/sources/openerp

sudo docker run -it --rm \
	--entrypoint=/bin/bash \
	-v /odoo/odoo-8.0/sources/openerp/:/mnt/extra-addons/openerp \
        jobiols/odoo-jeo:8.0 $*
