#!/bin/bash
##############################################################
# Extrae los odoo packages de la imagen al host
# Crea un directorio vacio dist-packages 
# entra en la imagen mapeando ese directorio, 
# una vez dentro de la imagen ejecutar esto:
# cp -r /usr/local/lib/python2.7/dist-packages/* /mnt/extra-addons/dist-packages/
# después salir de la imagen, inicializar git y agregar archivos al repo

sudo rm -r /odoo/odoo-8.0/sources/dist-packages
sudo mkdir /odoo/odoo-8.0/sources/dist-packages
sudo chmod -R o+w /odoo/odoo-8.0/sources/dist-packages
sudo chown jorge.jorge /odoo/odoo-8.0/sources/dist-packages

sudo docker run -it --rm \
	--entrypoint=/bin/bash \
	-v /odoo/odoo-8.0/sources/dist-packages/:/mnt/extra-addons/dist-packages \
        jobiols/odoo-jeo:8.0 $*
