#!/bin/bash
##############################################################
# Extract odoo sources to host

# cuando entra en la imagen correr esto:
# cp -r /usr/lib/python2.7/dist-packages/* /mnt/extra-addons/dist-packages/
# cp -r /usr/local/lib/python2.7/dist-packages/* /mnt/extra-addons/dist-local-packages/


# crea e inicializa un directorio
sudo rm -r /odoo/odoo-8.0/sources/dist-packages
sudo rm -r /odoo/odoo-8.0/sources/dist-local-packages

sudo mkdir /odoo/odoo-8.0/sources/dist-packages
sudo mkdir /odoo/odoo-8.0/sources/dist-local-packages

sudo chmod -R o+w /odoo/odoo-8.0/sources/dist-packages
sudo chmod -R o+w /odoo/odoo-8.0/sources/dist-local-packages

sudo chown jorge.jorge /odoo/odoo-8.0/sources/dist-packages
sudo chown jorge.jorge /odoo/odoo-8.0/sources/dist-local-packages

# entra en la imagen mapeando el directorio creado
sudo docker run -it --rm \
	--entrypoint=/bin/bash \
	-v /odoo/odoo-8.0/sources/:/mnt/extra-addons \
        jobiols/odoo-jeo:8.0 $*
