#!/bin/bash
#set -x

ERROR=0
CUSTOMER=$1
DB=$2
DATE=$(date +"%Y %m %d %H:%M")

docker stop odoo

docker run --rm -i \
  --name bkp \
  --link db:db \
  --volumes-from $CUSTOMER \
  -v /home/ubuntu/80/backup:/backup  \
  --env DBNAME=$DB jobiols/backup backup &> /home/ubuntu/$CUSTOMER.backup.log
if [ $? -ne 0 ]
  then
    ERROR=1
fi

docker start odoo

if [ $ERROR -ne 0 ]
  then
    echo -e "${DATE} Backup for client ${CUSTOMER} with db ${DB} failed!"
    exit 2
  else
    echo -e "${DATE} Backup for client ${CUSTOMER} with db ${DB} successfuly done"
fi
