#!/bin/bash
#set -x
readonly RED="\e[31m"
readonly YELLOW="\e[33m"
readonly GREEN="\e[32m"
readonly STD="\e[0m"

if [ $# -lt 2 ]
  then
    echo -e "${RED}Error! Too few arguments supplied!${STD}"
    echo -e "${STD}Command: sudo host-backup <customer> <db>"
    echo -e "${STD}--- or ---"
    echo -e "${STD}Command: sudo host-backup -c <configfile>"
    exit 1
fi

HASERROR=0

CUSTOMER=$1
DB=$2

echo -e "${YELLOW}Starting backup for database ${DB} of ${CUSTOMER}...${STD}"
docker run --rm -ti \
  --name bkp \
  --link db:db \
  --volumes-from $CUSTOMER \
  -v /home/ubuntu/80/backup:/backup  \
  --env DBNAME=$DB jobiols/backup backup &> /home/ubuntu/$CUSTOMER.backup.log
if [ $? -ne 0 ]
  then
    echo -e "${RED}Backup for ${CUSTOMER} with  ${DB} failed!${STD}"
    HASERROR=1
  else
    echo -e "${GREEN}Backup for ${DB} successful done${STD}"
fi

if [ "$HASERROR" = "1" ]
  then
    echo -e "${RED}Errors occured on backup process!!!!${STD}"
    exit 2
fi
