#!/bin/bash
###############################################
git status
echo -e "\n=== pulling scripts odoo v8 adhoc ==="
git pull
echo -e "\n=== installing scripts odoo v8 adhoc ==="
cp sd /usr/bin
cp odooenv /usr/bin
cp lib /usr/bin

