#!/bin/bash
# instalar odoo
cd
mkdir odoo80
cd odoo80
mkdir config
mkdir sources
mkdir postgresql
mkdir data_dir
chmod 777 -R config/ sources/ data_dir/
cd sources
git clone -b 8.0 https://github.com/ingadhoc/odoo-addons
git clone -b 8.0 https://github.com/ingadhoc/odoo-argentina
git clone -b 8.0 https://github.com/aeroo/aeroo_reports
git clone -b 8.0 https://github.com/OCA/server-tools
git clone -b 8.0 https://github.com/OCA/web

# Levantar container para convertir archivos de aeroo
sudo docker run -p 8989:8989 --name="aeroo_docs" --restart=always -d adhoc/aeroo-docs

# Levantar postgresql
sudo docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -v ~/odoo80/postgresql:/var/lib/postgresql/data --restart=always --name db-odoo80 postgres:9.4


# Crear archivo de configuracion despues del -- se pueden pasar todas las opciones que se quieran almacenar en el .conf, como por ejemplo path a nuevos addons que se ubiquen en la carpeta sources --addons-path)
sudo docker run --rm --link aeroo_docs:aeroo -p 127.0.0.1:8069:8069 -p 127.0.0.1:8072:8072 -v ~/odoo80/config:/etc/odoo -v ~/odoo80/sources:/mnt/extra-addons -v ~/odoo80/data_dir:/var/lib/odoo --link db-odoo80:db --name odoo80 adhoc/odoo-adhoc:8.0 -- --stop-after-init -s --addons-path=/mnt/extra-addons/odoo-argentina,/mnt/extra-addons/odoo-addons,/mnt/extra-addons/aeroo_reports,/mnt/extra-addons/server-tools,/mnt/extra-addons/web