#!/bin/bash
###############################################
sudo git status
echo -e "\n=== pulling scripts odoo v8 ==="
sudo git pull
echo -e "\n=== installing scripts odoo v8 ==="
sudo cp sd /usr/bin
sudo cp up-odoo /usr/bin
sudo cp down-odoo /usr/bin
sudo cp developer-mode /usr/bin
sudo cp session-mode /usr/bin
sudo cp host-backup /usr/bin
sudo cp host-restore /usr/bin
echo -e "\n=== scripts installed odoo v8 ==="
echo -e "\n=== pulling images odoo v8 ==="
sd pull jobiols/odoo:80
sd pull jobiols/aeroo_docs
sd pull jobiols/docker-odoo-backup
echo -e "\n=== images up to date ==="
