#!/bin/bash
#################################################3 

readonly RED="\e[31m"
readonly YELLOW="\e[33m"
readonly GREEN="\e[32m"
readonly STD="\e[0m"

function msginfo {
    echo -e "${STD}$1"
}
function msgrun {
    echo -e "${YELLOW}$1...${STD}"
}
function msgdone {
    echo -e "${GREEN}$1${STD}"
}
function msgerror {
    echo -e "${RED}ERROR: $1${STD}"
}

function get_port {
    for ((jj=0 ; jj<${#CLIENTS[@]} ; jj++))
    do
        if [ ${CLIENT} = ${CLIENTS[jj]} ] ; then
            PORT=${PORTS[jj]}
        fi
    done
}

#########################################################3

CLIENT1="str"
CLIENT2="makeover"
CLIENT3="adriana"

PORT1="8069"
PORT2="8068"
PORT3="8067"

PORTS=($PORT1 $PORT2 $PORT3)
CLIENTS=($CLIENT1 $CLIENT2 $CLIENT3)

# imagenes docker
AEROO="jobiols/aeroo-docs"
POSTGRES="postgres:9.4"
BACKUP="jobiols/backup"
ODOO="jobiols/odoo-adhoc:7.0"

# repositorios
ADDONS="jobiols/odoo-addons"
ARGENTINA="jobiols/odoo-argentina"
REPORTS="jobiols/aeroo_reports"
SERVERTOOLS="jobiols/server-tools"
WEB="jobiols/web"
ISO="jobiols/management-system"
KNOWLEDGE="jobiols/knowledge"
STR="jobiols/str"

IMAGES=($AEROO $POSTGRES $BACKUP $ODOO)
REPOS=($ADDONS $ARGENTINA $REPORTS $SERVERTOOLS $WEB $ISO $KNOWLEDGE $STR)
