#!/bin/bash
#################################################3 

readonly RED="\e[31m"
readonly YELLOW="\e[33m"
readonly GREEN="\e[32m"
readonly STD="\e[0m"

function msginfo {
    echo -e "${STD}$1"
}
function msgrun {
    echo -e "${YELLOW}$1...${STD}"
}
function msgdone {
    echo -e "${GREEN}$1${STD}"
}
function msgerror {
    echo -e "${RED}ERROR: $1${STD}"
}

function get_port {
#cliente
  if [ ${CLIENT} = "str" ] ; then
     PORT="8070"
  fi
# developer
  if [ ${CLIENT} = "kikai" ] ; then
     PORT="8069"
  fi
}

port=(8070 8069);
client=(str kikai);

AEROO="jobiols/aeroo-docs"
POSTGRES="postgres:9.4"
BACKUP="jobiols/backup"
ODOO="jobiols/odoo-adhoc:8.0"
IMAGES=($AEROO $POSTGRES $BACKUP $ODOO)

