#!/bin/bash
############################################################################################
#Include file lib in same dir as this file
. $(dirname $0)"/lib"

#TODO hacer backup automático

############################################################################################
function install_docker
{
    wget -qO- https://get.docker.com/ | sh
}


############################################################################################
function install_noip
{
    msgrun "\n installing no-ip on this server"
    apt-get install make
    apt-get -y install gcc
    cd /usr/local/src/
    wget http://www.noip.com/client/linux/noip-duc-linux.tar.gz
    tar xf noip-duc-linux.tar.gz
    cd noip-2.1.9-1/
    make install
    msginfo "Please answer some questions"
    #Please enter login/email: jobiols
    #Please enter password: veconceR
    #contestar preguntas sobre defaults y grupos.
    rm /usr/local/src/noip-duc-linux.tar.gz
    #Poner el script en init.d
    cp /usr/local/src/noip-2.1.9-1/debian.noip2.sh  /etc/init.d/
    #Make script executable
    chmod +x /etc/init.d/debian.noip2.sh
    #hacer que se ejecute al booteo
    update-rc.d debian.noip2.sh defaults
    #arrancar y parar el demonio
    msgrun "Starting no-ip daemon"
    /etc/init.d/debian.noip2.sh restart
    msgdone "no-ip service running"
}

############################################################################################
function list_all_clients
{
    msginfo "port----client--------------"
    for ((i=0 ; i<${#CLIENTS[@]} ; i++))
    do
        CLIENT=${CLIENTS[i]}
        get_port
        msginfo "${PORT} >  ${CLIENTS[i]}"
    done
    msginfo
    msginfo "images ----------------------"
    for ((i=0 ; i<${#IMAGES[@]} ; i++))
    do
        msginfo "  ${IMAGES[i]}"
    done
}

############################################################################################
#Levantar container para convertir archivos de aeroo $AEROO
function run_aeroo
{
    msgrun "Running ${AEROO}"
    if ! docker run -d \
	    -p 127.0.0.1:8989:8989 \
	    --name="aeroo_docs" \
    	--restart=always \
	    ${AEROO} ;
	then
	    msgerror "starting ${AEROO}"
 	    exit 1
 	fi
 	msgdone "${AEROO} up and running"
}

############################################################################################
#Levantar postgresql $POSTGRES
function run_postgres
{
    msgrun "Running ${POSTGRES}"
    if ! docker run -d \
	    -e POSTGRES_USER=odoo \
	    -e POSTGRES_PASSWORD=odoo \
	    -v ~/postgresql:/var/lib/postgresql/data \
	    --restart=always \
	    --name db-odoo \
	    ${POSTGRES} ;
	then
	    msgerror "starting ${POSTGRES}"
 	    exit 1
	fi
 	msgdone "${POSTGRES} up and running"
}

function run_database
{
    run_aeroo
    run_postgres
}

############################################################################################
#Levantar odoo
function run_odoo
{
    CLIENT=$OPTARG
    get_port

    msgrun "Running ${ODOO} on client ${CLIENT}"
    if ! docker run -d \
        --link aeroo_docs:aeroo \
        -p ${PORT}:8069 \
        -v ~/odoo80/${CLIENT}/config:/etc/odoo \
        -v ~/odoo80/${CLIENT}/data_dir:/var/lib/odoo \
        -v ~/odoo80/sources:/mnt/extra-addons \
        --link db-odoo:db \
        --restart=always \
        --name ${CLIENT} \
	    ${ODOO} -- --db-filter=${CLIENT}_.* ;
	then
        msgerror "running ${ODOO}"
 	    exit 1
	fi
 	msgdone "${ODOO} up and running on client ${CLIENT}"
}

############################################################################################
function do_pull
{
	msgrun "pulling all images for odoo V8 adhoc"
    for ((i=0 ; i<${#IMAGES[@]} ; i++))
    do
        msgrun "Pulling ${images[i]}"
	    if ! docker pull ${IMAGES[i]} ; then
 	        msgerror "fail pulling ${images[i]}"
 	        exit 1
 	    fi
    done
    msgdone "All images ok"
}

############################################################################################
function console_mode
{
    CLIENT=$(echo $OPTARG | cut -f1 -d,)
    DB=$(echo $OPTARG | cut -f2 -d,)
    echo $CLIENT
    echo $DB
    get_port

    msgrun "Running ${ODOO} on client ${CLIENT} in console mode"
    if ! docker run -it --rm \
        --link aeroo_docs:aeroo \
        -p ${PORT}:8069 \
        -v ~/odoo80/${CLIENT}/config:/etc/odoo \
        -v ~/odoo80/${CLIENT}/data_dir:/var/lib/odoo \
        -v ~/odoo80/sources:/mnt/extra-addons \
        --link db-odoo:db \
        --name ${CLIENT} \
	    ${ODOO} -- -d $DB -u all ;
	then
        msgerror "running ${ODOO}"
 	    exit 1
	fi
}

############################################################################################
function install_odoo
{
    msgrun "Installing odoo repos"
    cd
    mkdir postgresql
    mkdir -p odoo80/sources
    cd odoo80
    chmod 777 -R sources/
    cd sources
    for ((i=0 ; i<${#REPOS[@]} ; i++))
    do
        msgrun "Pulling ${REPOS[i]}"
	    if ! git clone -b 8.0 --depth 1 https://github.com/${REPOS[i]} ; then
 	        msgerror "fail pulling ${REPOS[i]}"
 	        exit 1
 	    fi
    done

#    git clone -b 8.0 --depth 1 https://github.com/${ADDONS}
#    git clone -b 8.0 --depth 1 https://github.com/${ARGENTINA}
#    git clone -b 8.0 --depth 1 https://github.com/${REPORTS}
#    git clone -b 8.0 --depth 1 https://github.com/${SERVERTOOLS}
#    git clone -b 8.0 --depth 1 https://github.com/${WEB}
    msgdone "Installing done"
}
############################################################################################
function run_image_client
{
    CLIENT=$OPTARG
    run_odoo
}

############################################################################################
function install_odoo_client
{
    msgrun "Installing odoo instance for client $OPTARG"
    CLIENT=$OPTARG

    cd ~/odoo80
    mkdir -p ${CLIENT}/config
    mkdir -p ${CLIENT}/data_dir
    chmod 777 -R ${CLIENT}/config/ ${CLIENT}/data_dir/

    msgrun "Creating config file for client $OPTARG"
    # Crear archivo de configuracion despues del -- se pueden pasar todas las opciones que se quieran almacenar en el .conf, como por ejemplo path a nuevos addons que se ubiquen en la carpeta sources --addons-path)
    docker run --rm  \
        -v ~/odoo80/${CLIENT}/config:/etc/odoo \
        -v ~/odoo80/sources:/mnt/extra-addons \
        -v ~/odoo80/${CLIENT}/data_dir:/var/lib/odoo \
        --name ${CLIENT} \
        ${ODOO} -- --stop-after-init -s \
        --addons-path=/mnt/extra-addons/odoo-argentina,/mnt/extra-addons/odoo-addons,/mnt/extra-addons/aeroo_reports,/mnt/extra-addons/server-tools,/mnt/extra-addons/web
    msgdone "Installing done"
}

############################################################################################
function stop_image_client
{
    CLIENT=$OPTARG
	msgrun "stop image for client ${CLIENT}"
    if ! docker stop ${CLIENT} ; then
        msgerror "fail stoping ${CLIENT}"
        exit 1
    fi
    if ! docker rm ${CLIENT} ; then
        msgerror "fail removing ${images[i]}"
        exit 1
    fi
    msgdone "client ${CLIENT} stopped"
}

function stop_database
{
    for name in db-odoo aeroo_docs
    do
        msgrun "stoping image ${name}"
        if ! docker stop ${name} ; then
            msgerror "fail stoping ${name}"
            exit 1
        fi
        if ! docker rm ${name} ; then
            msgerror "fail removing ${name}"
            exit 1
        fi
    done
}

function uninstall_all
{
    cd
    rm -r postgresql odoo80
}

############################################################################################
function help
{
    msginfo "Manages odoo environment in this VPS"
    msginfo
    msginfo "  -U           uninstall all files"
    msginfo "  -I           install odoo repos"
    msginfo "  -i [client]  install odoo instance for client"
    msginfo "  -R           run database and aeroo images"
    msginfo "  -r [client]  run image client"
    msginfo "  -S           stop database and aeroo images"
    msginfo "  -s [client]  stop image client"
    msginfo "  -p           pull all images"
    msginfo "  -n           install no-ip on this server"
    msginfo "  -d           install docker on this server"
    msginfo "  -l           list all clients in this server"
    msginfo "  -h           this help"
    msginfo "  -c [client,database]  update all for client and database"

    msginfo "###########################################"
    msginfo "   dir struct on host"
    msginfo "       ~/postgresql"
    msginfo "       ~/odoo80/sources"
    msginfo "       ~/odoo80/client/config"
    msginfo "       ~/odoo80/client/data_dir"
}

# test if user is root
if [[ $EUID -ne 0 ]]; then
   msgerror "This script must be run as root"
   exit 1
fi

while getopts "Ii:pnlhc:r:s:RSUd" opt; do
  case $opt in
    I)  install_odoo
        ;;
    i)  install_odoo_client
        ;;
    p)  do_pull
	    exit 0
	    ;;
    n)  install_noip
	    exit 0
	    ;;
    l)  list_all_clients
	    exit 0
	    ;;
    h)  help
        exit 0
        ;;
    c)  console_mode
        exit 0
        ;;
    r)  run_image_client
        ;;
    s)  stop_image_client
        ;;
    R)  run_database
        ;;
    S)  stop_database
        ;;
    U)  uninstall_all
        ;;
    d)  install_docker
        ;;
   [?]) help
        exit 1
        ;;
  esac
done