#!/bin/bash
#Include file lib in same dir as this file
. $(dirname $0)"/lib"

sudo docker run -it --rm \
        -p 8069:8069 \
        -v ~/odoo-OU_8.0/makeover/config:/etc/odoo \
        -v ~/odoo-OU_8.0/makeover/data_dir:/var/lib/odoo \
        -v ~/odoo-OU_8.0/makeover:/mnt/extra-addons \
        --link db-odoo:db \
        --entrypoint=/bin/bash \
        --name makeover \
	    jobiols/docker-openupgrade:8.0 $*
