#!/bin/bash
#for dir in $(ls)
#do
#  if [ -d $dir ] 
#  then
#	echo "Pullig repository --> " $dir 
#	cd $dir
#	git pull   
#	cd -
#  fi
#done
#set -x
readonly RED="\e[31m"
readonly YELLOW="\e[33m"
readonly GREEN="\e[32m"
readonly STD="\e[0m"

function msginfo {
    echo -e "${STD}$1"
}
function msgrun {
    echo -e "${YELLOW}$1...${STD}"
}
function msgdone {
    echo -e "${GREEN}$1${STD}"
}
function msgerror {
    echo -e "${RED}ERROR: $1${STD}"
}
###########################################################

msgrun "odoo"
cd ../odoo
git fetch upstream
git checkout 8.0
git merge upstream/8.0
git push origin 8.0
cd -

msgrun "odoomrp-wip"
cd ../odoomrp-wip
git fetch upstream
git checkout 8.0
git merge upstream/8.0
git push origin 8.0
cd -

msgrun "Python-Markdown"
cd ../Python-Markdown
git fetch upstream
git checkout master
git merge upstream/master
git push origin master
cd -


msgrun "account-financial-reporting"
cd ../account-financial-reporting
git fetch upstream
git checkout 8.0
git merge upstream/8.0
git push origin 8.0
cd -

msgrun "odoo-web"
cd ../odoo-web
git fetch upstream
git checkout 8.0
git merge upstream/8.0
git push origin 8.0
cd -

msgrun "odoo-argentina"
cd ../odoo-argentina
git fetch upstream
git checkout 8.0
git merge upstream/8.0
git push origin 8.0
cd -

msgrun "odoo-addons"
cd ../odoo-addons
git fetch upstream
git checkout 8.0
git merge upstream/8.0
git push origin 8.0
cd -

msgrun "aeroo_reports"
cd ../aeroo_reports
git fetch upstream
git checkout 8.0
git merge upstream/8.0
git push origin 8.0
cd -

msgrun "server-tools"
cd ../server-tools
git fetch upstream
git checkout 8.0
git merge upstream/8.0
git push origin 8.0
cd -

msgrun "web"
cd ../web
git fetch upstream
git checkout 8.0
git merge upstream/8.0
git push origin 8.0
cd -

msgrun "management-system"
cd ../management-system
git fetch upstream
git checkout 8.0
git merge upstream/8.0
git push origin 8.0
cd -

msgrun "knowledge"
cd ../knowledge
git fetch upstream
git checkout 8.0
git merge upstream/8.0
git push origin 8.0
cd -


