#!/bin/bash
#Include file lib in same dir as this file
. $(dirname $0)"/lib"

sudo docker run -it --rm \
       --volumes-from jeo \
       -v ~/odoo-8.0/jeo/backup:/backup \
       --link db-odoo:db \
       --env DBNAME=$1 \
       --env DATE=$2 \
       --entrypoint=/bin/bash \
       jobiols/backup
