#!/bin/bash
# Script to start odoo v8 docker instance
###############################################
echo -e "\n=== Starting odoo v8 ==="
sudo docker run -d --restart=always \
    --name db  \
    -e POSTGRES_PASSWORD=odoo \
    -e POSTGRES_USER=odoo \
    -v /home/ubuntu/80/data:/var/lib/postgresql/data \
    postgres:9.3.6

sudo docker run -d --restart=always -p 8989:8989 \
    --name aeroo_docs  \
    jobiols/aeroo_docs

sudo docker run -d --restart=always -p 80:8069 \
    --name odoo \
    --link db:db \
    --link aeroo_docs:aeroo_docs \
    -v /home/ubuntu/80/filestore:/home/odoo \
    jobiols/odoo:80