#!/bin/bash
############################################################################################
#Include file lib in same dir as this file
. $(dirname $0)"/lib"


for repo in odoo-argentina odoo-web docker-odoo-adhoc odoo-addons
do
  cd
  cd git-repos
  cd $repo
  msgrun "updating fork $repo"
  sudo git remote -v
  sudo git fetch upstream
  sudo git checkout 8.0
  sudo git merge upstream/8.0
  sudo git push origin 8.0
done
msgdone "all repos updated"
