{u'body': u'',
 u'labels': [],
 u'locked': False,
 u'title': u'issue de prueba sin body',
 u'url': u'https://api.github.com/repos/jobiols/custom/issues/1',
 u'labels_url': u'https://api.github.com/repos/jobiols/custom/issues/1/labels{/name}',
 u'created_at': u'2016-07-08T14:36:16Z',
 u'events_url': u'https://api.github.com/repos/jobiols/custom/issues/1/events',
 u'comments_url': u'https://api.github.com/repos/jobiols/custom/issues/1/comments',
 u'html_url': u'https://github.com/jobiols/custom/issues/1',
 u'comments': 0,
 u'number': 1,
 u'updated_at': u'2016-07-08T14:36:16Z',
 u'assignee': None,
 u'state': u'open',
 u'user': {
     u'following_url': u'https://api.github.com/users/jobiols/following{/other_user}',
     u'events_url': u'https://api.github.com/users/jobiols/events{/privacy}',
     u'organizations_url': u'https://api.github.com/users/jobiols/orgs',
     u'url': u'https://api.github.com/users/jobiols',
     u'gists_url': u'https://api.github.com/users/jobiols/gists{/gist_id}',
     u'html_url': u'https://github.com/jobiols',
     u'subscriptions_url': u'https://api.github.com/users/jobiols/subscriptions',
     u'avatar_url': u'https://avatars.githubusercontent.com/u/8525908?v=3',
     u'repos_url': u'https://api.github.com/users/jobiols/repos',
     u'received_events_url': u'https://api.github.com/users/jobiols/received_events',
     u'gravatar_id': u'',
     u'starred_url': u'https://api.github.com/users/jobiols/starred{/owner}{/repo}',
     u'site_admin': False, u'login': u'jobiols', u'type': u'User', u'id': 8525908,
     u'followers_url': u'https://api.github.com/users/jobiols/followers'},
 u'milestone': None,
 u'repository_url': u'https://api.github.com/repos/jobiols/custom',
 u'closed_at': None,
 u'assignees': [],
 u'id': 164544620}

> {u'body': u'comentario\r\nsegunda linea de comentario', u'labels': [], u'locked': False,
   u'title': u'issue de prueba sin body',
   u'url': u'https://api.github.com/repos/jobiols/custom/issues/1',
   u'labels_url': u'https://api.github.com/repos/jobiols/custom/issues/1/labels{/name}',
   u'created_at': u'2016-07-08T14:36:16Z',
   u'events_url': u'https://api.github.com/repos/jobiols/custom/issues/1/events',
   u'comments_url': u'https://api.github.com/repos/jobiols/custom/issues/1/comments',
   u'html_url': u'https://github.com/jobiols/custom/issues/1', u'comments': 1,
   u'number': 1, u'updated_at': u'2016-07-08T15:11:42Z', u'assignee': None,
   u'state': u'open', u'user': {
    u'following_url': u'https://api.github.com/users/jobiols/following{/other_user}',
    u'events_url': u'https://api.github.com/users/jobiols/events{/privacy}',
    u'organizations_url': u'https://api.github.com/users/jobiols/orgs',
    u'url': u'https://api.github.com/users/jobiols',
    u'gists_url': u'https://api.github.com/users/jobiols/gists{/gist_id}',
    u'html_url': u'https://github.com/jobiols',
    u'subscriptions_url': u'https://api.github.com/users/jobiols/subscriptions',
    u'avatar_url': u'https://avatars.githubusercontent.com/u/8525908?v=3',
    u'repos_url': u'https://api.github.com/users/jobiols/repos',
    u'received_events_url': u'https://api.github.com/users/jobiols/received_events',
    u'gravatar_id': u'',
    u'starred_url': u'https://api.github.com/users/jobiols/starred{/owner}{/repo}',
    u'site_admin': False, u'login': u'jobiols', u'type': u'User', u'id': 8525908,
    u'followers_url': u'https://api.github.com/users/jobiols/followers'},
   u'milestone': None,
   u'repository_url': u'https://api.github.com/repos/jobiols/custom', u'closed_at': None,
   u'assignees': [], u'id': 164544620}
